### ISSUE TITLE
Error with entering in admin panel  '/admin' 

### ISSUE THREAD

**Issue by karborator** [PhalconEye/phalconeye#108]
Hello, I just install phalcon eye , config and so on , but when I try to enter at Admin panel, nothing happens.I see the requirements for Phalcon 1.3.1, i'm using 1.3.4, but I don't think  this can be the problem.Also instead apache, I'm using nginx.   

Here is the error log :

 ````
[Tue, 03 Feb 15 17:22:26 +0200][ERROR] <wDIadF5> [Exception] Resource '/home/bender/projects/phalcon-eye/public/external/bootstrap/css/bootstrap.min.css' have the same source and target paths (File: /home/bender/projects/phalcon-eye/app/engine/Asset/Manager.php Line: [355])#0 [internal function]: Phalcon\Assets\Manager->output(Object(Phalcon\Assets\Collection), Array, 'css')
#1 /home/bender/projects/phalcon-eye/app/engine/Asset/Manager.php(355): Phalcon\Assets\Manager->outputCss('css')
#2 /home/bender/projects/phalcon-eye/app/var/cache/view/_home_bender_projects_phalcon-eye_app_modules_core_view_adminindex_index.volt.php(11): Engine\Asset\Manager->outputCss()
#3 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/home/bender/pr...', Array, true)
#4 [internal function]: Phalcon\Mvc\View->_engineRender(Array, 'AdminIndex/inde...', true, true, NULL)
#5 [internal function]: Phalcon\Mvc\View->render('AdminIndex', 'index', Array)
#6 /home/bender/projects/phalcon-eye/app/engine/Application.php(199): Phalcon\Mvc\Application->handle()
#7 /home/bender/projects/phalcon-eye/public/index.php(70): Engine\Application->getOutput()
#8 {main}
````
Also here is the html :

````
<!DOCTYPE html>
<html>
<head>
    <title>Admin panel</title>
    <meta charset="utf-8"><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(n,t,e){function r(e){if(!t[e]){var o=t[e]={exports:{}};n[e][0].call(o.exports,function(t){var o=n[e][1][t];return r(o?o:t)},o,o.exports)}return t[e].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<e.length;o++)r(e[o]);return r}({QJf3ax:[function(n,t){function e(n){function t(t,e,a){n&&n(t,e,a),a||(a={});for(var u=c(t),f=u.length,s=i(a,o,r),p=0;f>p;p++)u[p].apply(s,e);return s}function a(n,t){f[n]=c(n).concat(t)}function c(n){return f[n]||[]}function u(){return e(t)}var f={};return{on:a,emit:t,create:u,listeners:c,_events:f}}function r(){return{}}var o="nr@context",i=n("gos");t.exports=e()},{gos:"7eSDFh"}],ee:[function(n,t){t.exports=n("QJf3ax")},{}],gos:[function(n,t){t.exports=n("7eSDFh")},{}],"7eSDFh":[function(n,t){function e(n,t,e){if(r.call(n,t))return n[t];var o=e();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(n,t,{value:o,writable:!0,enumerable:!1}),o}catch(i){}return n[t]=o,o}var r=Object.prototype.hasOwnProperty;t.exports=e},{}],D5DuLP:[function(n,t){function e(n,t,e){return r.listeners(n).length?r.emit(n,t,e):(o[n]||(o[n]=[]),void o[n].push(t))}var r=n("ee").create(),o={};t.exports=e,e.ee=r,r.q=o},{ee:"QJf3ax"}],handle:[function(n,t){t.exports=n("D5DuLP")},{}],XL7HBI:[function(n,t){function e(n){var t=typeof n;return!n||"object"!==t&&"function"!==t?-1:n===window?0:i(n,o,function(){return r++})}var r=1,o="nr@id",i=n("gos");t.exports=e},{gos:"7eSDFh"}],id:[function(n,t){t.exports=n("XL7HBI")},{}],loader:[function(n,t){t.exports=n("G9z0Bl")},{}],G9z0Bl:[function(n,t){function e(){var n=v.info=NREUM.info;if(n&&n.licenseKey&&n.applicationID&&f&&f.body){c(d,function(t,e){t in n||(n[t]=e)}),v.proto="https"===l.split(":")[0]||n.sslForHttp?"https://":"http://",a("mark",["onload",i()]);var t=f.createElement("script");t.src=v.proto+n.agent,f.body.appendChild(t)}}function r(){"complete"===f.readyState&&o()}function o(){a("mark",["domContent",i()])}function i(){return(new Date).getTime()}var a=n("handle"),c=n(1),u=window,f=u.document,s="addEventListener",p="attachEvent",l=(""+location).split("?")[0],d={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-515.min.js"},v=t.exports={offset:i(),origin:l,features:{}};f[s]?(f[s]("DOMContentLoaded",o,!1),u[s]("load",e,!1)):(f[p]("onreadystatechange",r),u[p]("onload",e)),a("mark",["firstbyte",i()])},{1:11,handle:"D5DuLP"}],11:[function(n,t){function e(n,t){var e=[],o="",i=0;for(o in n)r.call(n,o)&&(e[i]=t(o,n[o]),i+=1);return e}var r=Object.prototype.hasOwnProperty;t.exports=e},{}]},{},["G9z0Bl"]);</script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />
````

**Comment by lantian** [comment]
Hi, there is some problems with 1.3.4 https://github.com/PhalconEye/cms/issues/88#issuecomment-62679589, sorry.

**Comment by mycrom** [comment]
You can make a few quick corrections to get this working right now before a better fix can be put in place. Check out https://github.com/PhalconEye/cms/pull/109

**Comment by lantian** [comment]
Must be ok in 0.5.0
